[project]
name = "weather"
version = "0.1.0"
description = "simple MCP weather to use in Claude"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6",
]
